export const LOADING_CAMPS="LOADING_CAMPS";
export const GET_ALL_CAMPS_SUCCESS = "GET_ALL_CAMPS_SUCCESS";
export const GET_ALL_CAMPS_FAIL = "GET_ALL_CAMPS_FAIL";


export const ADD_CAMP_SUCCESS = "ADD_CAMP_SUCCESS";
export const ADD_CAMP_FAIL = "ADD_CAMP_FAIL";


export const DELETE_CAMP_SUCCESS = "DELETE_CAMP_SUCCESS";
export const DELETE_CAMP_FAIL = "DELETE_CAMP_FAIL";

export const GET_ONE_CAMP_SUCCESS = "GET_ONE_CAMP_SUCCESS";
export const GET_ONE_CAMP_FAIL = "GET_ONE_CAMP_FAIL";

export const UPDATE_CAMP_SUCCESS = "UPDATE_CAMP_SUCCESS";
export const UPDATE_CAMP_FAIL = "UPDATE_CAMP_FAIL";